#!/bin/bash
# Builds StratIsland.app. No Xcode project needed — SPM builds the binary and we assemble
# the bundle by hand, which keeps the whole thing buildable from a terminal.
set -euo pipefail
cd "$(dirname "$0")"

APP="build/StratIsland.app"
# Version comes from the release tag when there is one (scripts/release.sh passes it);
# the build number is the commit count, so it only ever goes up.
VERSION="${VERSION:-1.0}"
BUILD="$(git rev-list --count HEAD 2>/dev/null || echo 1)"
BIN="$(swift build -c release --show-bin-path)/StratIsland"

echo "==> building"
swift build -c release

echo "==> assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/StratIsland"

# Kode Mono is committed to the repo under Fonts/ — unlike the OCR A Extended it replaced,
# it is SIL OFL licensed, so redistribution is explicit. The app falls back to a
# system-installed copy, then to Menlo, if it is absent.
if [ -f Fonts/KodeMono-Variable.ttf ]; then
  cp Fonts/KodeMono-Variable.ttf "$APP/Contents/Resources/KodeMono-Variable.ttf"
  cp Fonts/KodeMono-OFL.txt "$APP/Contents/Resources/KodeMono-OFL.txt"
  echo "    bundled Kode Mono"
else
  echo "    WARNING: Fonts/KodeMono-Variable.ttf not found — falling back to Menlo"
fi

# The menu bar icon is bundled verbatim. It is a *template* asset: monochrome with a real
# alpha channel, because macOS recolours it for the current appearance and throws the colour
# away. Generated from the Stratcore mark's alpha at 36 px so 18 pt stays crisp on Retina.
# Without it the status item falls back to a text glyph.
if [ -f MenuBarIcon.png ]; then
  cp MenuBarIcon.png "$APP/Contents/Resources/MenuBarIcon.png"
  echo "    bundled MenuBarIcon.png"
fi

# Bundled so "Install hooks…" in the status menu needs no clone — a DMG or Homebrew install
# already carries everything it runs. install-hooks.sh does `cd "$(dirname "$0")"`, so it
# finds stratisland-notify.py next to it inside Resources unchanged.
if [ -f scripts/install-hooks.sh ] && [ -f scripts/stratisland-notify.py ]; then
  cp scripts/install-hooks.sh "$APP/Contents/Resources/install-hooks.sh"
  cp scripts/stratisland-notify.py "$APP/Contents/Resources/stratisland-notify.py"
  chmod +x "$APP/Contents/Resources/install-hooks.sh" "$APP/Contents/Resources/stratisland-notify.py"
  echo "    bundled install-hooks.sh + stratisland-notify.py"
else
  echo "    WARNING: scripts/install-hooks.sh or stratisland-notify.py not found — Install hooks… will be disabled"
fi

# The app icon is generated from the 1024pt master at package time rather than committing a
# binary .icns that would have to be regenerated by hand whenever the master changes. It is
# an agent app with no Dock tile, so this is what Finder, alerts and Get Info show.
ICON_SRC="notchicon-iOS-Default-1024x1024@1x.png"
if [ -f "$ICON_SRC" ]; then
  ICONSET="$(mktemp -d)/AppIcon.iconset"
  mkdir -p "$ICONSET"
  for size in 16 32 128 256 512; do
    sips -z $size $size "$ICON_SRC" --out "$ICONSET/icon_${size}x${size}.png" >/dev/null
    sips -z $((size * 2)) $((size * 2)) "$ICON_SRC" \
      --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null
  done
  iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"
  rm -rf "$(dirname "$ICONSET")"
  echo "    built AppIcon.icns"
else
  echo "    WARNING: $ICON_SRC not found — bundling no icon"
fi

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>StratIsland</string>
    <key>CFBundleDisplayName</key><string>StratIsland</string>
    <key>CFBundleIdentifier</key><string>com.stratcore.stratisland</string>
    <key>CFBundleExecutable</key><string>StratIsland</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>__VERSION__</string>
    <key>CFBundleVersion</key><string>__BUILD__</string>
    <key>LSMinimumSystemVersion</key><string>14.0</string>
    <key>LSUIElement</key><true/>
    <key>NSAppleEventsUsageDescription</key>
    <string>StratIsland brings the Terminal tab that owns a CLI session to the front when you click it.</string>
</dict>
</plist>
PLIST

sed -i '' -e "s/__VERSION__/$VERSION/" -e "s/__BUILD__/$BUILD/" "$APP/Contents/Info.plist"

# A Developer ID signature is stable across rebuilds, so the Automation grant for Terminal
# survives them; an ad-hoc one changes every build. Set SIGN_IDENTITY to pick a specific
# identity, or SIGN_IDENTITY=- to force ad-hoc. Without a Developer ID in the keychain
# (anyone building from source) this falls back to ad-hoc, which is fine for local use.
if [ -z "${SIGN_IDENTITY:-}" ]; then
  SIGN_IDENTITY="$(security find-identity -v -p codesigning 2>/dev/null \
    | sed -n 's/.*"\(Developer ID Application: [^"]*\)".*/\1/p' | head -1)"
  SIGN_IDENTITY="${SIGN_IDENTITY:--}"
fi

if [ "$SIGN_IDENTITY" = "-" ]; then
  echo "==> signing (ad-hoc)"
  codesign --force --sign - "$APP"
else
  # Hardened runtime and a secure timestamp are both required for notarization.
  echo "==> signing as $SIGN_IDENTITY"
  codesign --force --options runtime --timestamp \
    --entitlements StratIsland.entitlements --sign "$SIGN_IDENTITY" "$APP"
fi
codesign --verify --strict "$APP"

echo "==> done: $APP"
