#!/bin/bash
# Builds StratIsland.app. No Xcode project needed — SPM builds the binary and we assemble
# the bundle by hand, which keeps the whole thing buildable from a terminal.
set -euo pipefail
cd "$(dirname "$0")"

APP="build/StratIsland.app"
BIN="$(swift build -c release --show-bin-path)/StratIsland"

echo "==> building"
swift build -c release

echo "==> assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BIN" "$APP/Contents/MacOS/StratIsland"

# OCR A Extended is copied from the system at package time rather than committed, so a
# font of uncertain redistribution license never enters the repo. The app falls back to a
# system-installed copy, then to Menlo, if it is absent.
if [ -f /Library/Fonts/OCRAEXT.TTF ]; then
  cp /Library/Fonts/OCRAEXT.TTF "$APP/Contents/Resources/OCRAEXT.TTF"
  echo "    bundled OCR A Extended"
else
  echo "    WARNING: /Library/Fonts/OCRAEXT.TTF not found — falling back to Menlo"
fi

# The app icon is generated from the 1024pt master at package time rather than committing a
# binary .icns that would have to be regenerated by hand whenever the master changes. It is
# an agent app with no Dock tile, so this is what Finder, alerts and Get Info show.
ICON_SRC="notchicon-iOS-Default-1024x1024@1x.png"
if [ -f "$ICON_SRC" ]; then
  ICONSET="$(mktemp -d)/AppIcon.iconset"
  mkdir -p "$ICONSET"
  for size in 16 32 128 256 512; do
    sips -z $size $size "$ICON_SRC" --out "$ICONSET/icon_${size}x${size}.png" >/dev/null
    sips -z $((size * 2)) $((size * 2)) "$ICON_SRC" \
      --out "$ICONSET/icon_${size}x${size}@2x.png" >/dev/null
  done
  iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"
  rm -rf "$(dirname "$ICONSET")"
  echo "    built AppIcon.icns"
else
  echo "    WARNING: $ICON_SRC not found — bundling no icon"
fi

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key><string>StratIsland</string>
    <key>CFBundleDisplayName</key><string>StratIsland</string>
    <key>CFBundleIdentifier</key><string>com.stratcore.stratisland</string>
    <key>CFBundleExecutable</key><string>StratIsland</string>
    <key>CFBundleIconFile</key><string>AppIcon</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>1.0</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>14.0</string>
    <key>LSUIElement</key><true/>
    <key>NSAppleEventsUsageDescription</key>
    <string>StratIsland brings the Terminal tab that owns a CLI session to the front when you click it.</string>
</dict>
</plist>
PLIST

echo "==> signing (ad-hoc)"
codesign --force --deep --sign - "$APP"

echo "==> done: $APP"
